# Generated by Django 3.2.6 on 2021-10-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('details', models.CharField(max_length=250)),
                ('near_railway', models.CharField(max_length=250)),
                ('near_airport', models.CharField(max_length=250)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=250)),
                ('distance_from_place', models.CharField(max_length=250)),
                ('images', models.FileField(upload_to='uploads/')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='southkerala.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='southkerala.blog')),
            ],
        ),
    ]
