# Generated by Django 3.2.6 on 2021-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='details',
            field=models.TextField(),
        ),
    ]
