# Generated by Django 3.2.6 on 2021-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0006_remove_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
