# Generated by Django 3.2.6 on 2021-10-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0007_auto_20211004_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
