# Generated by Django 3.2.6 on 2021-10-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0008_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagepath', models.FileField(upload_to='uploads/')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='southkerala.blog')),
            ],
        ),
    ]
