# Generated by Django 3.2.6 on 2021-10-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
