# Generated by Django 3.2.6 on 2021-10-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0010_delete_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=250)),
                ('distance_from_place', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('rating', models.IntegerField()),
                ('images', models.FileField(upload_to='uploads/')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='southkerala.blog')),
            ],
        ),
    ]
