# Generated by Django 3.2.6 on 2021-10-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('southkerala', '0012_enquiry_suggesions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='name',
            new_name='uname',
        ),
    ]
